apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: testing
  labels:
    app: microservice-web
spec:
  containers:
    - name: web-hello
      image: bernardosecades/hello-dude:v1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
